import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { AdminAuthProvider } from "./Context/AdminAuthContext";
import { AdminGuard } from "./Context/AdminGuard";
import { Toaster } from "react-hot-toast";
import { ConfirmProvider } from "./Context/confirmContext";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Batu Petshop AdminPanel",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased ${jost.className}`}>
        <AdminAuthProvider>
            <ConfirmProvider>
            {children}
            </ConfirmProvider>
          <Toaster position="top-right" reverseOrder={false} />
        </AdminAuthProvider>
      </body>
    </html>
  );
}
